<a href="https://colab.research.google.com/github/dong-wook96/homework/blob/master/%EC%97%B4%EC%9C%A0%EC%B2%B4%EA%B3%B5%ED%95%99%EC%8B%A4%ED%97%98-2015009998-HW04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numba
import numpy as np

   
x = np.arange(1,10)
a = int(input())

def gugudan(x,a):
  x*a
print(x*a)

%timeit numba.jit(gugudan(x,a))

for i in range (1,10):
  print(a*i)
%timeit a*i


2
[ 2  4  6  8 10 12 14 16 18]
The slowest run took 13.13 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.5 µs per loop
2
4
6
8
10
12
14
16
18
10000000 loops, best of 3: 41.5 ns per loop


In [45]:
x=int(input("입력"))
for i in range (1,10):
  print(x*i)

%timeit x*i

입력3
3
6
9
12
15
18
21
24
27
The slowest run took 28.06 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 36.8 ns per loop


In [44]:
import numpy as np
x = np.arange(1,10)
a = int(input())
print(x*a)
%timeit x*a

2
[ 2  4  6  8 10 12 14 16 18]
The slowest run took 20.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 935 ns per loop


In [58]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'


/usr/local/cuda-10.1/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so


In [0]:
import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.1/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so"


In [62]:
import numpy as np
from numba import vectorize

@vectorize(['int64(int64, int64)'], target='cuda')
def gugudan(x,a):
  return x*a

y = np.arange(1,10)
a = int(input())

print(y*a)

%timeit gugudan(y,a)


3
[ 3  6  9 12 15 18 21 24 27]


CudaSupportError: ignored